name: Bedwars
main: de.Paluffle.Main
version: 1.0
commands:
  bedwars:
    description: Zeigt die Befehle an.
  ichbineinpandah:
    description: .
  updater:
    description: updater
  switch:
    description: beta
